// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF_Z-Es5wZQKELcGvPL7kBGLgOmHyhhPQ',
    appId: '1:230413250726:web:64e2e620a69f0f836dc467',
    messagingSenderId: '230413250726',
    projectId: 'pmms-g6',
    authDomain: 'pmms-g6.firebaseapp.com',
    storageBucket: 'pmms-g6.firebasestorage.app',
    measurementId: 'G-NBY6KLYEY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqQkkbblO1hoLP6qS03mTvtXZFjl7QvaY',
    appId: '1:230413250726:android:fc22b6c328c1f9b36dc467',
    messagingSenderId: '230413250726',
    projectId: 'pmms-g6',
    storageBucket: 'pmms-g6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxuTd6KLJBAhltbnTAvSfsx7cT_gpUr3A',
    appId: '1:924114016561:ios:1cfdb30c166af7b9193810',
    messagingSenderId: '924114016561',
    projectId: 'bite-app-94377',
    storageBucket: 'bite-app-94377.firebasestorage.app',
    iosBundleId: 'com.example.pmmsG6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxuTd6KLJBAhltbnTAvSfsx7cT_gpUr3A',
    appId: '1:924114016561:ios:1cfdb30c166af7b9193810',
    messagingSenderId: '924114016561',
    projectId: 'bite-app-94377',
    storageBucket: 'bite-app-94377.firebasestorage.app',
    iosBundleId: 'com.example.pmmsG6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF_Z-Es5wZQKELcGvPL7kBGLgOmHyhhPQ',
    appId: '1:230413250726:web:10b80ebb76eb8e4e6dc467',
    messagingSenderId: '230413250726',
    projectId: 'pmms-g6',
    authDomain: 'pmms-g6.firebaseapp.com',
    storageBucket: 'pmms-g6.firebasestorage.app',
    measurementId: 'G-57PNJ4YTQT',
  );

}